### ISSUE TITLE
Materials should be resources

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#10]
**Is your feature request related to a problem? Please describe.**
Now you need to select the material parameters for each `component::Material`, but we should be able to create the materials before, and select between one of them.

**Feature description**
A  `resource::Material` should exist, and one of the existing can be selected for the  `component::Material`.

**Tasks**
- [x] Create `resource::Material`
- [x] Change `component::Material`
- [x] UI module
  - [x] Create material resource
  - [x] Edit `resource::Material`
  - [x] Delete `resource::Material`
  - [x] Select `resource::Material` from  `component::Material`
- [x] File module
  - [x] Serialize `resource::Material`
  - [x] Deserialize `resource::Material`

**Comment by brenocq** [comment]
**Creating material resource**
```c++
res::Material::CreateInfo info;
info.albedo = vec3(1.0f, 0.8f, 0.6f);
info.metallic = 0.5f;
info.roughness = 0.5f;
res::Material* rmat = res::create<res::Material>("myMaterial", info);
```

**Creating material component**
```c++
EntityId entity = createEntity();
comp::Material* mat = comp::addEntityComponent<comp::Material>(entity);
mat->setResource(rmat);
```

**Getting material resource from material component**
```c++
res::Material* rmat = mat->getResource();
```

**Comment by brenocq** [comment]
Material component UI:
![DeepinScreenshot_select-area_20220813150637](https://user-images.githubusercontent.com/17342434/184480823-4eb803d7-4c8f-44f3-9df5-587a84052c6f.png)
