### ISSUE TITLE
Refactor io::Http to work cross-platform

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#14]
**Is your feature request related to a problem? Please describe.**
Today http requests are being made using **cpprestsdk**, but the project is not building properly for _Windows_ and _MacOS_.

**Feature description**
we want `atta` to implement the http interface, so that it is easy to use and we can change the underlying implementation in the future if necessary.

**Tasks**
- [ ] Decide if should continue using cpprestsdk or change to another library
- [ ] Fix build in _Windows_ and _MacOS_
- [ ] Implement http interface
- [ ] Refactor `open from published` to use `atta::io::Http` (opening projects from Github)

**Comment by brenocq** [comment]
Change from cpprestsdk to cpp-netlib in commit be83a6b3fc90ba1eff15f7e5db532b6f2de3611e. The .cpp file with the `Http` implementation is being chosen at compilation time (.h is always http.h).
- `httpNet.cpp`: if it is building for the web
- `httpCppNetlib.cpp`: if it is building with cpp-netlib support
- `httpNull.cpp`: if network is not supported
