### ISSUE TITLE
Version handling

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#16]
**Is your feature request related to a problem? Please describe.**
It is only possible to install one atta version in the computer right now, which can be bad if we have projects that were developed in different versions.

**Feature description**
Now we can only install one version of atta, but we should be able to install multiple versions in the same machine because they may be incompatible between each other, and we may want to install another version to run a specific project.

**Tasks**
- [x] Install atta with version
  - [x] `/usr/local/include/atta-0.0.3.0/`
  - [x] `/usr/local/include/atta-0.0.3.0/extern`
  - [x] `/usr/local/share/atta-0.0.3.0/`
  - [x] `/usr/local/bin/atta-0.0.3.0` and `/usr/local/bin/atta`
- [x] Be able to select atta version to link to the project with cmake. Eg: `find_package(atta 0.0.3.0 REQUIRED)`
- [x] UI see current version (Help menu)
- [x] Open different atta versions from atta
- [x] Uninstall versions

**Ideas for the future**
- Install different atta versions from the atta application (download and install from could)
- Change default atta version from the atta application (`/usr/bin/atta-0.0.3.0` to `/usr/bin/atta`)
- Should suggest options to restart atta with another version if trying to open project made with another version

**Comment by brenocq** [comment]
To install multiple version, files are installed to:
- resources: `/usr/local/share/atta-X.X.X.X/`
- libs: `/usr/local/lib/atta-X.X.X.X/`
- includes: `/usr/local/include/atta-X.X.X.X/atta/`
- ext_includes: `/usr/local/include/atta-X.X.X.X/extern/`
- binaries
  -  `/usr/lib/bin/atta`
  - `/usr/lib/bin/atta-X.X.X.X`
  - `/usr/lib/bin/atta_test`
  - `/usr/lib/bin/atta_test-X.X.X.X`

This way the default atta program will be the last installed (overwriting `atta` executable), but it is also possible to run older versions
