### ISSUE TITLE
Web project

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#17]
**Is your feature request related to a problem? Please describe.**
Now the web build is not able to open projects.

**Feature description**
It should be possible to open projects when using the web build, probably it is necessary to compile the project and link statically to the atta executable. It should be possible to build atta with projects linked statically, so that the final build is only able to execute that project.

**Tasks**
- [x] Build atta with project linked statically
- [x] Disable possibility to open other projects when compiled specifically to a specific project
- [x] DIsable hot-reload when compiled statically
- [x] Make web build work with project linked statically

**Comment by brenocq** [comment]
## Registering scripts
Because we are not linking dynamic libraries with the scripts, we need another way to register scripts.

### Project dynamic target linking
If it is dynamic library, we look for a function `Script* createScript()` defined in the library. We can search for this function for each of the project libraries

### Project static target linking
It turns out to be a bit more tricky to register scripts when the project is linked statically. 
 - We can't define `Script* createScript()` multiple times, so maybe define this function with other names? But how to find which files to include and what is the function name? A lot of corner cases
 - The final solution creates a `scriptSystem/scripts.h` file at compilation time with the include for all project target headers. When `ScriptManager` includes this file, all the inline variables are solved (which calls a function to register the script). We are now registering the scripts to the `ScriptManager` using one inline variable per script header.

**Comment by brenocq** [comment]
## Building emscripten with static project
- Could not find atta installed -> now the project being built will always use the current atta being built, not the installed one.
- The project `.atta` file and `resources/` folder are copied to the we build (`.data`). They are located in `/project/` in the web filesystem.

**Comment by brenocq** [comment]
Web static build was finally able to execute projects, but the colors were wrong in WebGL. Turn out the problem was because we needed to copy the vector data to a temporary variable before sending to the GPU (not sure why).

Before:
![before](https://user-images.githubusercontent.com/17342434/173409500-3b8f8bbf-a9df-4188-889e-66a3b18a5019.gif)


After:
![after](https://user-images.githubusercontent.com/17342434/173409514-958ec566-fcb8-4aa5-8a2d-f035a1d349e8.gif)
