### ISSUE TITLE
Script parallelization

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#21]
**Is your feature request related to a problem? Please describe.**
Now all the scripts are being performed sequentially with only one thread. 

**Feature description**
It should be possible to distribute script execution across CPU and GPU.
- CPU: Select how many thread pools to use.
- GPU: CUDA threads

**Tasks**
Add a  list of tasks that should be performed to implement the feature.
- [ ] Define how to structure GPU/CPU
- [ ] Thread manager
- [ ] CPU worker
- [ ] Be able to select how many thread workers
- [ ] Dynamic script with GPU?
