### ISSUE TITLE
Update texture resources

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#22]
**Is your feature request related to a problem? Please describe.**
It is not easy to create one texture, and edit it while the simulation is running. For example, if we want to change the floor texture as agents walk over it.

**Feature description**
It should be easy to create texture resources that are not saved in disk (.jpg, .png files). It should be possible to update their data while the simulation is running in an easy way.

**Tasks**
- [x] Create texture resources (without need to create file)
- [x] Update Graphics Image when texture resource is changed
- [x] Save texture resource to file

**Notes:**
For some reason the texCoord for the FastRenderer is always 0.
