### ISSUE TITLE
Boids example

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#29]
**Description**
For the release 0.2.0.0 a set of examples are being developed to check how easy it is to use atta.
The changelog in the comments will list all the changes when developing this project, mainly bug fixes and code refactoring.
The repository for this project can be found here: https://github.com/brenocq-atta/boids
The web build can be found here: https://atta.brenocq.com/projects/brenocq-atta/boids

**Tasks**
- [x] Boids workings
- [x] Movable obstacles
- [x] Show force field in the background
- [x] Inspect selected boid (plot data)
- [x] Show boid view radius
- [x] Make sure web build works
- [x] Update published web build on commit

**Thoughts for the future**
- Update the texture in GPU
- Use physics module to get neighbour boids
- Use physics module to cast collision avoidance rays
- Implement in 3D
- Be able to run only a fraction of the clones in a factory? (so we can add boids dynamically)

**Comment by brenocq** [comment]
**Atta changelog**
- Scripts now are being loaded properly
- `cmp::getPrototypeFactory(cmp::Entity)` renamed to `cmp::getFactory(cmp::Entity)`
- Fix crash when material name is `""`
- Now `scr::ProjectScript::onLoad` is called only after the components are deserialized from the `.atta` file
- Now it is possible to use literal `""_sid` without being in the atta scope

**Comment by brenocq** [comment]
![Image](https://user-images.githubusercontent.com/17342434/184535530-fa48b0a2-6bb4-4649-9b63-08416fc88e5f.gif)

**Comment by brenocq** [comment]
![ezgif com-gif-maker (27)](https://user-images.githubusercontent.com/17342434/184541959-bcd4beb2-2aa8-49cc-b642-3d73bd59b1a6.gif)

**Comment by brenocq** [comment]
![Uploading DeepinScreenshot_select-area_20220814191657.png…]()
