### ISSUE TITLE
Tutorial example

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#30]
**Description**
For the release 0.2.0.0 a set of examples are being developed to check how easy it is to use atta.
The changelog in the comments will list all the changes when developing this project, mainly bug fixes and code refactoring.
The repository for this project can be found here: https://github.com/brenocq-atta/tutorial

**Tasks**
- [x] Cube factory example
- [x] Logging example
- [x] Simple script example
- [x] Image resource example
- [x] Entity spawn example
- [x] Graphics drawer example
- [x] Plots example
- [x] Materials example (fix rendering)

**Comment by brenocq** [comment]
**Atta changelog**
- Fixes
  - Mesh combo now being shown

**Comment by brenocq** [comment]
![Image](https://user-images.githubusercontent.com/17342434/185344069-b3c2d5da-ec1b-441a-abf9-52064518e65a.gif)

**Comment by brenocq** [comment]
All examples were implemented. There are still some problems with the rendering, but I will postpone the fix for the future.
