### ISSUE TITLE
Linux scripting

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#37]
**Is your feature request related to a problem? Please describe.**
The hot-reload function is not working properly on Linux.

**Feature description**
The hot-reload should work on Linux and be tested in different Linux distributions.

_NOTE: Only g++ will be supported for now._

**Tasks**
- [x] Fix project script not reloading
- [x] Check if component struct can change
- [x] Be able to rebuild when included files are changed
- [x] Test hot-reload with different Linux distributions
  - [x] Ubuntu 18.04
  - [x] Ubuntu 22.04
  - [x] Fedora 36
  - [x] Arch 2022.09.03
