### ISSUE TITLE
Windows scripting

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#38]
**Feature description**
The hot-reload should be implemented for Windows. 

**Tasks**
- [ ] Implement `file::WindowsFileWatcher`
- [ ] Implement `script::WindowsCompiler`
- [ ] Implement `script::WindowsLinker`
- [ ] Make sure it works as expected

**Comment by brenocq** [comment]
I will be closing this issue as new features are now being tracked in another place.
