### ISSUE TITLE
MacOS scripting

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#39]
**Feature description**
The hot-reload should be implemented for MacOS. 

**Tasks**
- [ ] Implement `file::MacosFileWatcher`
- [ ] Implement `script::MacosCompiler`
- [ ] Implement `script::MacosLinker`
- [ ] Make sure it works as expected

**Comment by brenocq** [comment]
I will be closing this issue as new features are now being tracked in another place.
