### ISSUE TITLE
Physics Box2D

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#40]
**Feature description**
The Box2D is already integrated into atta, but we need to improve the physics module interface, and provide an UI to configure Box2D. Testing if it works properly with the newer atta versions is also necessary.

**Tasks**
- [ ] Create obstacle avoidance example
- [ ] Create sumo example
- [ ] Box2D configuration UI
- [ ] Check physics drawer

**Comment by brenocq** [comment]
I will be closing this issue as new features are now being tracked in another place.
