### ISSUE TITLE
Refactor project serialization

### ISSUE THREAD

**Issue by brenocq** [brenocq/atta#9]
**Is your feature request related to a problem? Please describe.**
Should be easier to add more data to be serialized/deserialized to the `.atta` file. Currently we need a lot of lines of code.

**Feature description**
Implement a class helper to deserialize/deserialize, it should have the following features:
 - Dictionaries and lists (similar to json)
 - Support to dump binary data (images, structs, etc)
 - Be possible to ignore unknown section
 - Be able to detect corrupted files

**Tasks**
- [x] Think about how to structure serializer/deserializer helpers
- [x] Interface populate section
- [x] Basic section to std::string
- [x] Implement serializer
- [x] Implement deserializer
